class HomeController < ApplicationController
  before_action :authenticate_user!
  layout 'home'

  def index
  end

  # Redirect can use the killer url paths autogenerated
  def home
    redirect_to(:home_url)

    # Use the byebug method to get a terminal incase of any issue
    # byebug
  end

  def getbug
    # byebug
  end
end
