class HomeController < ApplicationController
  before_action :authenticate_user!
  def killer
  end

  # Redirect can use the killer url paths autogenerated
  def home2
    redirect_to(:home_killer_url)

    # Use the byebug method to get a terminal incase of any issue
    # byebug
  end

  def getbug
    # byebug
  end
end
